blank_issues_enabled: no
contact_links:
  - name: Test1
    url: https://github.com/demateopablo/Testing/issues/new?assignees=&labels=&template=https://github.com/demateopablo/Testing/blob/main/.github/ISSUE_TEMPLATE/FormTest.yml&title=AP+%22X%22+-+Descripci%C3%B3n
    about: Test.
    
    
